import React from 'react'
import Head from 'next/head'

export default function head() {
    return (
        <React.Fragment>
            <Head>
                <title>Xythonix App</title>
                <meta name="description" content="Generated by Xythonix" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </React.Fragment>
    )
}